# Generated by Django 5.2.16 on 2026-07-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
