# Generated by Django 5.2.16 on 2026-07-20 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome or Bootstrap icon class, for example fa-solid fa-laptop-code.', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Business categories',
                'db_table': 'business_categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='business_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('sample_hex', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX colour such as #2563EB or an eight-digit value such as #2563EBFF.', regex='^#(?:[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$')])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Colour families',
                'db_table': 'color_families',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='color_family_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='DesignStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'design_styles',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='design_style_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('native_name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Language code, for example en, tw, gaa or fr.', max_length=10, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='language_active_idx'), models.Index(fields=['is_default'], name='language_default_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'moods',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='mood_active_idx')],
            },
        ),
    ]
