# Generated by Django 5.2.16 on 2026-07-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('enquiry_type', models.CharField(choices=[('GENERAL', 'General Enquiry'), ('TECHNICAL_SUPPORT', 'Technical Support'), ('ACCOUNT_SUPPORT', 'Account Support'), ('PALETTE_SUPPORT', 'Palette Support'), ('EXPORT_SUPPORT', 'Export Support'), ('BUSINESS_ENQUIRY', 'Business Enquiry'), ('FEEDBACK', 'Feedback'), ('PARTNERSHIP', 'Partnership'), ('OTHER', 'Other')], default='GENERAL', max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('SPAM', 'Spam')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_enquiries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='enquiry_status_idx'), models.Index(fields=['created_at'], name='enquiry_created_at_idx'), models.Index(fields=['email'], name='enquiry_email_idx'), models.Index(fields=['enquiry_type'], name='enquiry_type_idx')],
            },
        ),
    ]
