# Generated by Django 5.2.16 on 2026-07-20 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('palettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_mode', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='LIGHT', max_length=10)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('business_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_requests', to='core.businesscategory')),
                ('design_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_requests', to='core.designstyle')),
                ('generated_palette', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_request', to='palettes.palette')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_requests', to='core.mood')),
                ('preferred_color_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_recommendation_requests', to='core.colorfamily')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRequestAvoidedColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_request_avoidances', to='core.colorfamily')),
                ('recommendation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoided_color_records', to='recommendations.recommendationrequest')),
            ],
            options={
                'db_table': 'recommendation_request_avoided_colors',
                'ordering': ['color_family'],
            },
        ),
        migrations.AddField(
            model_name='recommendationrequest',
            name='avoided_color_families',
            field=models.ManyToManyField(blank=True, related_name='avoided_by_recommendation_requests', through='recommendations.RecommendationRequestAvoidedColor', to='core.colorfamily'),
        ),
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('theme_mode', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='LIGHT', max_length=10)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_rules', to='core.businesscategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendation_rules', to=settings.AUTH_USER_MODEL)),
                ('design_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_rules', to='core.designstyle')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_rules', to='core.mood')),
                ('preferred_color_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_recommendation_rules', to='core.colorfamily')),
                ('template_palette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_rules', to='palettes.palette')),
            ],
            options={
                'db_table': 'recommendation_rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='recommendationrequest',
            name='selected_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_requests', to='recommendations.recommendationrule'),
        ),
        migrations.CreateModel(
            name='RecommendationRuleAvoidedColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_rule_avoidances', to='core.colorfamily')),
                ('recommendation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoided_color_records', to='recommendations.recommendationrule')),
            ],
            options={
                'db_table': 'recommendation_rule_avoided_colors',
                'ordering': ['color_family'],
            },
        ),
        migrations.AddField(
            model_name='recommendationrule',
            name='avoided_color_families',
            field=models.ManyToManyField(blank=True, related_name='avoided_by_recommendation_rules', through='recommendations.RecommendationRuleAvoidedColor', to='core.colorfamily'),
        ),
        migrations.AddConstraint(
            model_name='recommendationrequestavoidedcolor',
            constraint=models.UniqueConstraint(fields=('recommendation_request', 'color_family'), name='unique_request_avoided_color'),
        ),
        migrations.AddIndex(
            model_name='recommendationrequest',
            index=models.Index(fields=['user', '-created_at'], name='rec_request_user_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrequest',
            index=models.Index(fields=['business_category', 'theme_mode', '-created_at'], name='rec_request_business_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrequest',
            index=models.Index(fields=['session_key', '-created_at'], name='rec_request_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationruleavoidedcolor',
            constraint=models.UniqueConstraint(fields=('recommendation_rule', 'color_family'), name='unique_rule_avoided_color'),
        ),
        migrations.AddIndex(
            model_name='recommendationrule',
            index=models.Index(fields=['business_category', 'mood', 'design_style', 'theme_mode'], name='rec_rule_match_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrule',
            index=models.Index(fields=['is_active', '-priority'], name='rec_rule_active_idx'),
        ),
    ]
