# Generated by Django 5.2.16 on 2026-07-20 00:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to generate the slug automatically.', max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('PRESET', 'Preset'), ('RECOMMENDATION', 'Recommendation'), ('RECOMMENDATION_TEMPLATE', 'Recommendation Template'), ('COMMUNITY_COPY', 'Community Copy'), ('DUPLICATE', 'Duplicate')], default='MANUAL', max_length=30)),
                ('theme_mode', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='LIGHT', max_length=10)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted')], default='PRIVATE', max_length=10)),
                ('moderation_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REMOVED', 'Removed')], default='DRAFT', max_length=20)),
                ('allow_export', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palettes', to='core.businesscategory')),
                ('dominant_color_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominant_palettes', to='core.colorfamily')),
                ('owner', models.ForeignKey(blank=True, help_text='The owner may be empty for system presets and recommendation templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palettes', to=settings.AUTH_USER_MODEL)),
                ('source_palette', models.ForeignKey(blank=True, help_text='Original palette when this palette was copied, duplicated, or generated from a template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_palettes', to='palettes.palette')),
            ],
            options={
                'db_table': 'palettes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaletteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('ACCENT', 'Accent'), ('BACKGROUND', 'Background'), ('SURFACE', 'Surface'), ('HEADING', 'Heading'), ('BODY_TEXT', 'Body Text'), ('MUTED_TEXT', 'Muted Text'), ('BORDER', 'Border'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('INFO', 'Info')], max_length=20)),
                ('hex_value', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX colour such as #2563EB or an eight-digit value such as #2563EBFF.', regex='^#(?:[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$')])),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='palettes.palette')),
            ],
            options={
                'verbose_name': 'Palette colour',
                'verbose_name_plural': 'Palette colours',
                'db_table': 'palette_colors',
                'ordering': ['role'],
            },
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['owner', '-created_at'], name='palette_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['business_category'], name='palette_business_idx'),
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['dominant_color_family'], name='palette_color_family_idx'),
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['source_palette'], name='palette_source_palette_idx'),
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['source_type'], name='palette_source_type_idx'),
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['theme_mode'], name='palette_theme_idx'),
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['visibility', 'moderation_status', 'is_published'], name='palette_gallery_idx'),
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['is_featured', 'is_active'], name='palette_featured_idx'),
        ),
        migrations.AddConstraint(
            model_name='palette',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), models.Q(('visibility', 'PRIVATE'), _negated=True), _connector='OR'), name='palette_published_not_private'),
        ),
        migrations.AddConstraint(
            model_name='palette',
            constraint=models.CheckConstraint(condition=models.Q(('is_featured', False), models.Q(('is_published', True), ('moderation_status', 'APPROVED')), _connector='OR'), name='palette_featured_is_approved'),
        ),
        migrations.AddIndex(
            model_name='palettecolor',
            index=models.Index(fields=['palette'], name='palette_color_palette_idx'),
        ),
        migrations.AddIndex(
            model_name='palettecolor',
            index=models.Index(fields=['role'], name='palette_color_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='palettecolor',
            constraint=models.UniqueConstraint(fields=('palette', 'role'), name='unique_palette_color_role'),
        ),
    ]
