# Generated by Django 5.2.16 on 2026-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
