# Generated by Django 5.2.16 on 2026-07-20 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy_type', models.CharField(choices=[('DUPLICATE', 'Duplicate'), ('COMMUNITY_COPY', 'Community Copy'), ('PRESET_APPLY', 'Preset Apply'), ('RECOMMENDATION_APPLY', 'Recommendation Apply')], max_length=30)),
                ('copied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palette_copy_records', to=settings.AUTH_USER_MODEL)),
                ('destination_palette', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin_copy_record', to='palettes.palette')),
                ('source_palette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copy_records', to='palettes.palette')),
            ],
            options={
                'db_table': 'palette_copies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['copied_by', '-created_at'], name='palette_copy_user_idx'), models.Index(fields=['source_palette', '-created_at'], name='palette_copy_source_idx'), models.Index(fields=['copy_type', '-created_at'], name='palette_copy_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaletteExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_format', models.CharField(choices=[('CSS', 'CSS Variables'), ('JSON', 'JSON'), ('SCSS', 'SCSS'), ('BOOTSTRAP', 'Bootstrap'), ('TAILWIND', 'Tailwind CSS'), ('REACT', 'React Theme'), ('ANDROID_COMPOSE', 'Android Compose')], max_length=30)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('palette_snapshot', models.JSONField(blank=True, help_text='Stores temporary palette data for guest exports or historical audit purposes.', null=True)),
                ('palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_records', to='palettes.palette')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palette_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palette_exports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['palette', '-created_at'], name='palette_export_palette_idx'), models.Index(fields=['user', '-created_at'], name='palette_export_user_idx'), models.Index(fields=['export_format', '-created_at'], name='palette_export_format_idx'), models.Index(fields=['session_key', '-created_at'], name='palette_export_session_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaletteLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='palettes.palette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palette_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palette_likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['palette', '-created_at'], name='palette_like_palette_idx'), models.Index(fields=['user', '-created_at'], name='palette_like_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'palette'), name='unique_user_palette_like')],
            },
        ),
        migrations.CreateModel(
            name='PaletteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed'), ('ACTION_TAKEN', 'Action Taken')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='palettes.palette')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_palette_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_palette_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palette_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['palette', 'status'], name='palette_report_palette_idx'), models.Index(fields=['status', '-created_at'], name='palette_report_status_idx'), models.Index(fields=['reviewed_by'], name='palette_report_reviewer_idx')],
                'constraints': [models.UniqueConstraint(fields=('reported_by', 'palette'), name='unique_user_palette_report')],
            },
        ),
        migrations.CreateModel(
            name='PaletteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='palettes.palette')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palette_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palette_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['palette', '-viewed_at'], name='palette_view_palette_idx'), models.Index(fields=['user', '-viewed_at'], name='palette_view_user_idx'), models.Index(fields=['session_key', '-viewed_at'], name='palette_view_session_idx')],
            },
        ),
    ]
