# Generated by Django 5.2.16 on 2026-07-21 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('palettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='palettelike',
            name='unique_user_palette_like',
        ),
        migrations.AddField(
            model_name='palettelike',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='palettelike',
            name='session_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='palettelike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palette_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='palettelike',
            index=models.Index(fields=['session_key', '-created_at'], name='palette_like_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='palettelike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'palette'), name='unique_user_palette_like_new'),
        ),
        migrations.AddConstraint(
            model_name='palettelike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('session_key', 'palette'), name='unique_session_palette_like'),
        ),
    ]
